tts:
  default_param:
    tts_config: "/root/harmoni_catkin_ws/src/HARMONI/harmoni_actuators/harmoni_tts/content/config.json"
    tts_model: "/root/harmoni_catkin_ws/src/HARMONI/harmoni_actuators/harmoni_tts/content/tts_model.pth.tar"
    vocoder_config: "/root/harmoni_catkin_ws/src/HARMONI/harmoni_actuators/harmoni_tts/content/config_vocoder.json"
    vocoder_model: "/root/harmoni_catkin_ws/src/HARMONI/harmoni_actuators/harmoni_tts/content/vocoder_model.pth.tar"
    use_cuda: False
    verbose: False
    speedup: 1.1
    outdir: "$(find harmoni_tts)/temp_data"
