# This is a configuration file describing the id of the child of each repo
harmoni:
  bot: ["default"]
  tts: ["default"]
  web: ["default"]
  stt: ["default"]
  #face_detect: ["default"]
hardware:
  microphone: ["default"]
  #camera: ["default"]
  face: ["default"]
  speaker: ["default"]
  # gesture: ["default"]
pytree:
  bot: ["default"]
  tts: ["default"]
  web: ["default"]
  stt: ["default"]
  microphone: ["default"]
  camera: ["object","person"]
  face: ["default"]
  speaker: ["voice_robot","external_sound"]
  gesture: ["default"]
  yolo: ["default"]
  custom_yolo: ["default"]
