pytree:
  default_param:
    interaction: "minja_ppi_test" #or meditation or ppi
    user_name: "Sam"
    session: "session1" #session1_empathic
    researcher_name: "Minja"
    scene: 0
    condition :  0 #0: non-empathic, 1: empathic

