pytree:
  default_param:
    interaction: "new_test" #or meditation or ppi
    user_name: "Cassandra"
    session: "session1" 
    researcher_name: "Minja"
    scene: 0
    condition :  0 #0: non-empathic, 1: empathic

