pytree:
  default_param:
    interaction: "minja_ppi_test" #or meditation or ppi
    user_name: "Micol"
    session: "session2" #session1_empathic, session1
    researcher_name: "Minja"
    scene: 0
    condition :  0 #0: non-empathic, 1: empathic

