imageai_yolo:
  default_param: #param for detection with plane YOLOv3
    subscriber_id: "default"
    frame_per_second: 30
    output_file_name: "temp_output"
    log_progress: True
    minimum_percentage_probability: 50 #minimum percentage for recognizing objects
    return_detected_frame: False #if true, allows you to obtain the detected video frame as a Numpy array
    model_path: "/root/harmoni_catkin_ws/src/HARMONI/harmoni_models/yolo/"
    temp_path: "/root/harmoni_catkin_ws/src/HARMONI/harmoni_detectors/harmoni_imageai/temp_data/"
